#!/usr/bin/env node
'use strict';
// Build from the checked-out SF source. No network, model calls or project writes.
const fs = require('node:fs');
const path = require('node:path');
const { execFileSync } = require('node:child_process');
const { createHash } = require('node:crypto');
const ROOT = path.resolve(__dirname, '..');
const SKILLS = { 'manual-test': 'sf-testing', commit: 'sf-commit', 'srs-to-sd': 'sf-srs-to-sd' };
function write(file, value) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, value);
}
function walk(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).sort((a,b) => a.name.localeCompare(b.name)).flatMap(e => {
    if (['__pycache__', '.DS_Store'].includes(e.name) || e.name.endsWith('.pyc')) return [];
    const p = path.join(dir, e.name);
    if (e.isSymbolicLink()) throw new Error(`Unexpected symlink: ${p}`);
    return e.isDirectory() ? walk(p) : [p];
  });
}
function frontmatter(text) {
  const match = text.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n/);
  if (!match) throw new Error('Missing source frontmatter');
  const desc = match[1].match(/^description:\s*(.*)(?:\n((?:[ \t]+[^\n]*\n?)*))?/m);
  if (!desc) throw new Error('Missing source description');
  let description = desc[1].trim();
  if (/^[>|][-+]?$/.test(description)) description = (desc[2] || '').trim().replace(/\s+/g, ' ');
  else if (description.startsWith('"')) description = JSON.parse(description);
  return { description, body: text.slice(match[0].length) };
}
function transform(text) {
  text = text.replaceAll('${CLAUDE_PLUGIN_ROOT}', '${SPEC_FLOW_ROOT}')
    .replaceAll('$ARGUMENTS', '<user arguments>')
    .replace(/\/sf:([a-z-]+)/g, '$sf-$1')
    .replaceAll('AskUserQuestion', 'the available Codex question tool (or a concise question in chat)')
    .replaceAll('bin/flow-tools.cjs', 'scripts/flow-tools.cjs')
    .replaceAll('bin/task-master', 'scripts/task-master.cjs');
  for (const [oldName, name] of Object.entries(SKILLS)) text = text.replaceAll(`skills/${oldName}`, `skills/${name}`);
  // Quote the variable portion, including when it appears within a shell assignment.
  text = text.replace(/(?<!["'])\$\{SPEC_FLOW_ROOT\}/g, '"${SPEC_FLOW_ROOT}"');
  return text;
}
function build(out = path.join(ROOT, 'dist/codex')) {
  out = path.resolve(out);
  // Never recursively erase an arbitrary directory supplied by a caller.
  if (fs.existsSync(out) && !fs.existsSync(path.join(out, '.sf-codex-build'))) {
    if (fs.readdirSync(out).length) throw new Error(`Output is not an SF build directory: ${out}`);
  }
  fs.mkdirSync(out, { recursive: true });
  const dest = path.join(out, 'plugins/sf');
  fs.rmSync(dest, { recursive: true, force: true });
  write(path.join(out, '.sf-codex-build'), 'Generated by scripts/build-codex.cjs\n');
  const hashes = {};
  function copyTree(dir, target = dir, convert = false) {
    for (const file of walk(path.join(ROOT, dir))) {
      const raw = fs.readFileSync(file);
      hashes[path.relative(ROOT, file)] = createHash('sha256').update(raw).digest('hex');
      const to = path.join(dest, target, path.relative(path.join(ROOT, dir), file));
      write(to, convert && file.endsWith('.md') ? transform(raw.toString()) : raw);
      fs.chmodSync(to, fs.statSync(file).mode & 0o777);
    }
  }
  for (const dir of ['bin', 'lib', 'templates', '.claude-plugin']) copyTree(dir);
  copyTree('hooks', 'upstream-hooks');
  copyTree('agents', 'references/agents', true);
  copyTree('docs', 'docs', true);
  copyTree('commands', 'references/commands', true);
  // Provider setup is a host concern. Fail on upstream shape changes instead of
  // silently shipping executable Claude setup commands into the Codex workflow.
  const initFile = path.join(dest, 'references/commands/init.md');
  let init = fs.readFileSync(initFile, 'utf8');
  const providerBlock = /   b\. \*\*Default to the keyless[\s\S]*?(?=\n4\. \*\*Report)/;
  if (!providerBlock.test(init)) throw new Error('Codex init mapping needs review: upstream provider block changed');
  init = init.replace(providerBlock, '   b. **Use the current Codex session as the host.** The engine defaults to `agent-native`; task operations emit a GenerationSpec for Codex to fulfill. Do not set Claude provider/model roles or change existing project model settings.\n');
  init = init.replace(/^   - \*\*Provider:\*\*.*$/m, '   - **Provider:** the current Codex session handles `agent-native` generation; no separate API key is needed. Existing explicit provider modes remain unchanged.');
  write(initFile, init);
  copyTree('adapters/codex/runtime', 'scripts');
  const runtime = fs.readFileSync(path.join(ROOT, 'adapters/codex/runtime.md'), 'utf8');
  function skill(name, description, body) {
    const header = `---\nname: ${name}\ndescription: ${JSON.stringify(description.replaceAll("->", "→").replace(/[<>]/g, ""))}\n---\n\n`;
    write(path.join(dest, 'skills', name, 'SKILL.md'), header + runtime + '\n\n' + body);
  }
  for (const [oldName, name] of Object.entries(SKILLS)) {
    copyTree(`skills/${oldName}`, `skills/${name}`, true);
    const source = frontmatter(fs.readFileSync(path.join(ROOT, `skills/${oldName}/SKILL.md`), 'utf8'));
    let body = transform(source.body);
    if (oldName === 'srs-to-sd') {
      body = body.replace(/## Dependencies[\s\S]*$/, '## Dependencies\nUse the bundled testing helpers, `scripts/flow-tools.cjs` and `scripts/task-master.cjs`. Task generation uses the current Codex session in agent-native mode. This package registers no MCP server and fetches no external task engine.\n');
    }
    skill(name, transform(source.description), body);
  }
  for (const file of walk(path.join(ROOT, 'commands'))) {
    if (!file.endsWith('.md')) continue;
    const command = path.basename(file, '.md');
    const source = frontmatter(fs.readFileSync(file, 'utf8'));
    skill(`sf-${command}`, transform(source.description), `Read and follow [${command}](../../references/commands/${command}.md).`);
  }
  const upstream = JSON.parse(fs.readFileSync(path.join(ROOT, '.claude-plugin/plugin.json')));
  const manifest = JSON.parse(fs.readFileSync(path.join(ROOT, 'adapters/codex/plugins/sf/.codex-plugin/plugin.json')));
  manifest.version = upstream.version;
  manifest.author = upstream.author;
  write(path.join(dest, '.codex-plugin/plugin.json'), JSON.stringify(manifest, null, 2) + '\n');
  const hooks = { hooks: {} };
  for (const [event, matcher] of [['UserPromptSubmit', null], ['PreToolUse', 'Edit|Write|apply_patch'], ['PostToolUse', 'Bash']]) {
    hooks.hooks[event] = [{ ...(matcher ? { matcher } : {}), hooks: [{ type: 'command', command: 'node "${PLUGIN_ROOT}/scripts/hook.cjs"', timeout: 30 }] }];
  }
  write(path.join(dest, 'hooks/hooks.json'), JSON.stringify(hooks, null, 2) + '\n');
  write(path.join(out, '.agents/plugins/marketplace.json'), JSON.stringify({
    name: 'spec-flow-codex', interface: { displayName: 'Spec Flow for Codex' },
    plugins: [{ name: 'sf', source: { source: 'local', path: './plugins/sf' }, policy: { installation: 'AVAILABLE', authentication: 'ON_INSTALL' }, category: 'Productivity' }]
  }, null, 2) + '\n');
  for (const file of ['LICENSE', 'adapters/codex/runtime.md', '.claude-plugin/plugin.json', 'scripts/build-codex.cjs', 'adapters/codex/plugins/sf/.codex-plugin/plugin.json']) {
    hashes[file] = createHash('sha256').update(fs.readFileSync(path.join(ROOT, file))).digest('hex');
  }
  let commit = null;
  try { commit = execFileSync('git', ['rev-parse', 'HEAD'], { cwd: ROOT, encoding: 'utf8' }).trim(); } catch {}
  write(path.join(dest, 'build-info.json'), JSON.stringify({ upstreamVersion: upstream.version, sourceCommit: commit, adapterVersion: 1, sourceHashes: hashes }, null, 2) + '\n');
  write(path.join(dest, 'LICENSE'), fs.readFileSync(path.join(ROOT, 'LICENSE')));
  return { out, plugin: dest, version: upstream.version };
}
module.exports = { build, transform, frontmatter };
if (require.main === module) {
  if (process.argv.length > 3) throw new Error('Usage: node scripts/build-codex.cjs [output-directory]');
  console.log(JSON.stringify(build(process.argv[2]), null, 2));
}
